language: node_js
node_js:
  - "5"
script:
  - npm run test
branches:
  only:
    - master
after_script:
 babel-node node_modules/isparta/bin/isparta cover --report text --report html node_modules/mocha/bin/_mocha -- --reporter dot -r ignore-styles -r ./test/setup.js --recursive && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

